name: CI

on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: latest
          activate-environment: test
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          conda install -c conda-forge pytest requests decorator google-auth vcrpy aiohttp google-auth-oauthlib pre-commit google-cloud-core google-api-core google-api-python-client -y
          pip install git+https://github.com/intake/filesystem_spec --no-deps
          conda list
          conda --version

      - name: Install gcsfs
        run: python setup.py install

      - name: Run Tests
        run: GCSFS_RECORD_MODE=none py.test -vv gcsfs

      - name: Run pre-commit hooks
        run: pre-commit run --all-file
